name: Test Coveralls

on: ["push", "pull_request"]

env:
  NODE_COVERALLS_DEBUG: 1

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Coveralls
      uses: coverallsapp/github-action@master
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-endpoint: https://enterprise-demo.coveralls.io
        path-to-lcov: ./coverage/lcov/coveralls-demo-ruby-enterprise.lcov

    - name: Coveralls Test Access to Github Actions
      run: |
        curl --fail --header "Accept: application/vnd.github.machine-man-preview+json" \
        --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        --request GET --url "https://api.github.com/installation/repositories"
